kind: pipeline
type: docker
name: default

steps:
  - name: build-coverage-image
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f Dockerfile.coverage -t localhost:5000/rust-coverage:latest .
      - docker push localhost:5000/rust-coverage:latest

  - name: coverage
    image: localhost:5000/rust-coverage:latest
    commands:
      - rustc --version
      - cargo --version
      # List workspace members and run tarpaulin for each
      - |
        cargo tarpaulin \
          --all-features \
          --timeout 120 \
          --out Html \
          --out Xml \
          --out Json \
          --fail-under 70 \
          --engine llvm \
          --skip-clean \
          --ignore-config \
          --target-dir /tmp/cargo \
          --output-dir coverage \
          --workspace || FAILED=true

    volumes:
      - name: cache-coverage
        path: /tmp/cargo

  - name: publish-coverage
    image: plugins/sftp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      src_dir: coverage/
      dest_dir: coverage/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}
      strip_components: 1

volumes:
  - name: cache-coverage
    host:
      path: /tmp/cache-coverage
  - name: dockersock
    host:
      path: /var/run/docker.sock
