kind: pipeline
type: docker
name: default

steps:
  - name: coverage
    image: rust:1.85.1-slim
    commands:
      - rustc --version
      - cargo --version
      - apt-get update && apt-get install -y libssl-dev pkg-config lld jq
      - cargo install --target-dir /tmp/cargo --version 0.32.3 cargo-tarpaulin
      # List workspace members and run tarpaulin for each
      - |
        set -e
        mkdir -p coverage
        for pkg in $(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name'); do
          echo "Running coverage for $pkg"
          cargo tarpaulin \
            --all-features \
            --timeout 120 \
            --out Html \
            --out Xml \
            --out Json \
            --output-dir coverage/$pkg \
            --fail-under 70 \
            --exclude-files 'tests/*' \
            --exclude-files 'examples/*' \
            --exclude-files '**/*_test.rs' \
            --engine llvm \
            --skip-clean \
            --target-dir /tmp/cargo \
            -p "$pkg" || FAILED=true
        done

    volumes:
      - name: cache-coverage
        path: /tmp/cargo

  - name: publish-coverage
    image: plugins/s3
    settings:
      bucket: coverage
      source: coverage/**/*
      target: /${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}
      path_style: true
      endpoint:
        from_secret: minio_endpoint
      access_key:
        from_secret: minio_access_key
      secret_key:
        from_secret: minio_secret_key

volumes:
  - name: cache-coverage
    host:
      path: /tmp/cache-coverage
