kind: pipeline
type: docker
name: default

steps:
  - name: coverage
    image: rust:1.85.1-slim
    commands:
      - rustc --version
      - cargo --version
      - apt-get update && apt-get install -y libssl-dev pkg-config lld jq
      # Install tarpaulin with specific version for stability
      - cargo install --version 0.32.3 cargo-tarpaulin
      # Run tarpaulin with better configuration
      - >
        cargo tarpaulin
        --all-features
        --workspace
        --timeout 120
        --out Html
        --out Xml
        --out Json
        --output-dir coverage
        --fail-under 70
        --exclude-files 'tests/*'
        --exclude-files 'examples/*'
        --exclude-files '**/*_test.rs'
        --engine llvm || FAILED=true
    volumes:
      - name: cache
        path: /drone/src/.cargo

volumes:
  - name: cache
    temp: {}
