kind: pipeline
type: docker
name: default

steps:
  - name: coverage
    image: rust:1.85.1-slim
    commands:
      - rustc --version
      - cargo --version
      - apt-get update && apt-get install -y libssl-dev pkg-config lld jq
      - cargo install --target-dir /tmp/cargo --version 0.32.3 cargo-tarpaulin
      # List workspace members and run tarpaulin for each
      - |
        set -e
        mkdir -p coverage
        cargo metadata --no-deps --format-version 1 | \
          jq -c '.packages[] | {name: .name, manifest_path: .manifest_path}' | \
          while read pkginfo; do
            pkg=$(echo "$pkginfo" | jq -r .name)
            manifest=$(echo "$pkginfo" | jq -r .manifest_path)
            pkgdir=$(dirname "$manifest")
            echo "Running coverage for $pkg in $pkgdir"
            cd "$pkgdir"
            cargo tarpaulin \
              --all-features \
              --timeout 120 \
              --out Html \
              --out Xml \
              --out Json \
              --output-dir "$OLDPWD/coverage/$pkg" \
              --fail-under 70 \
              --exclude-files 'tests/*' \
              --exclude-files 'examples/*' \
              --exclude-files '**/*_test.rs' \
              --engine llvm \
              --skip-clean \
              --ignore-config \
              --target-dir /tmp/cargo || FAILED=true
            cd "$OLDPWD"
          done

    volumes:
      - name: cache-coverage
        path: /tmp/cargo

  - name: publish-coverage
    image: plugins/s3
    settings:
      bucket: coverage
      source: coverage/**/*
      target: /${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}
      path_style: true
      endpoint:
        from_secret: minio_endpoint
      access_key:
        from_secret: minio_access_key
      secret_key:
        from_secret: minio_secret_key

volumes:
  - name: cache-coverage
    host:
      path: /tmp/cache-coverage
