kind: pipeline
type: docker
name: default

steps:
  - name: build-coverage-image
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f Dockerfile.coverage -t localhost:5000/rust-coverage:latest .
      - docker push localhost:5000/rust-coverage:latest

  - name: coverage
    image: localhost:5000/rust-coverage:latest
    environment:
      SSH_PASSWORD:
        from_secret: ssh_password
      SSH_USER:
        from_secret: ssh_user
      SSH_HOST:
        from_secret: ssh_hostname
    commands:
      - rustc --version
      - cargo --version
      - mkdir coverage
      - touch coverage/dumfile.yaml
      - mkdir -p ~/.ssh
      - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - sshpass -p "$SSH_PASSWORD" scp -r coverage/ $SSH_USER@$SSH_HOST:coverage/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}
      # List workspace members and run tarpaulin for each
      # - |
      #   cargo tarpaulin \
      #     --all-features \
      #     --timeout 120 \
      #     --out Html \
      #     --out Xml \
      #     --out Json \
      #     --fail-under 70 \
      #     --engine llvm \
      #     --skip-clean \
      #     --ignore-config \
      #     --target-dir /tmp/cargo \
      #     --output-dir coverage \
      #     --workspace || FAILED=true

    volumes:
      - name: cache-coverage
        path: /tmp/cargo


volumes:
  - name: cache-coverage
    host:
      path: /tmp/cache-coverage
  - name: dockersock
    host:
      path: /var/run/docker.sock
