FROM rust:1.85.1-slim

RUN apt-get update && \
    apt-get install -y libssl-dev pkg-config lld jq python3-pip python3-venv 
RUN cargo install --version 0.32.3 cargo-tarpaulin 
RUN python3 -m venv /opt/venv 
RUN /opt/venv/bin/pip install merge-cobertura
RUN /opt/venv/bin/pip install pycobertura 

ENV PATH="/opt/venv/bin:$PATH"
