FROM rust:1.85.1-slim

RUN apt-get update && \
    apt-get install -y libssl-dev pkg-config lld jq python3-pip && \
    cargo install --version 0.32.3 cargo-tarpaulin && \
    pip3 install cobertura-merge
